all: 
	gcc ./ex_0_getting_started.c -o ./ex_0_getting_started.exe
	gcc ./ex_1_variables.c -o ./ex_1_variables.exe
	gcc ./ex_2_assigment.c -o ./ex_2_assigment.exe
	gcc ./ex_3_printf.c -o ./ex_3_printf.exe
	gcc ./ex_4_arithmetic_operators.c -o ./ex_4_arithmetic_operators.exe
	gcc ./ex_5_logic_operators.c -o ./ex_5_logic_operators.exe
	gcc ./ex_6_conditions.c -o ./ex_6_conditions.exe
	gcc ./ex_7_blocks.c -o ./ex_7_blocks.exe
	gcc ./ex_8_loops.c -o ./ex_8_loops.exe
	gcc ./ex_9_break_continue.c -o ./ex_9_break_continue.exe
	gcc ./ex_10_procedures.c -o ./ex_10_procedures.exe
	gcc ./ex_11_functions.c -o ./ex_11_functions.exe
	gcc ./ex_12_constants.c -o ./ex_12_constants.exe

clean:
	rm -f *.exe
	rm -f *.o