all: 
	gcc ./ex_0_ptrs_on_structs.c -o ./ex_0_ptrs_on_structs.exe
	gcc ./ex_1_strings.c -o ./ex_1_strings.exe
	gcc ./ex_2_input_string.c -o ./ex_2_input_string.exe
	gcc ./ex_3_files_read.c -o ./ex_3_files_read.exe
	gcc ./ex_4_define.c -o ./ex_4_define.exe

clean:
	rm -f *.exe
	rm -f *.o