all: 
	gcc ./ex_0_getting_addr.c -o ./ex_0_getting_addr.exe
	gcc ./ex_1_pointer_type.c -o ./ex_1_pointer_type.exe
	gcc ./ex_2_pointers_operations.c -o ./ex_2_pointers_operations.exe
	gcc ./ex_3_pointers_and_constants.c -o ./ex_3_pointers_and_constants.exe
	gcc ./ex_4_pointer_transfer.c -o ./ex_4_pointer_transfer.exe
	gcc ./ex_5_array.c -o ./ex_5_array.exe
	gcc ./ex_6_array_transfer.c -o ./ex_6_array_transfer.exe
	gcc ./ex_7_matrix_implementation.c -o ./ex_7_matrix_implementation.exe
	gcc ./ex_8_2d_array.c -o ./ex_8_2d_array.exe
	gcc ./ex_9_scanf.c -o ./ex_9_scanf.exe

clean:
	rm -f *.exe
	rm -f *.o