all: 
	gcc ./ex_0_global_variables.c -o ./ex_0_global_variables.exe
	gcc ./ex_1_machine_eps.c -o ./ex_1_machine_eps.exe
	gcc ./ex_2_printf_features.c -o ./ex_2_printf_features.exe
	gcc ./ex_3_procedural_type.c -o ./ex_3_procedural_type.exe
	gcc ./ex_4_math_lib.c -o ./ex_4_math_lib.exe
	gcc ./ex_5_structs.c -o ./ex_5_structs.exe

clean:
	rm -f *.exe
	rm -f *.o